### ISSUE TITLE
Custom endpoints seems not working in API v2.0.17

### ISSUE THREAD

**Issue by yarick2000** [directus/docs#104]
Hello, I was trying to make a call to example custom endpoint which code is located in public\extensions\custom\endpoints\_example.php file. I've renamed _example.php to example.php and was trying to make an authenticated GET call to the following route: /myproject/custom/example.
Basing on the code inside of this file I should get a response with the following array:
['item 1','item 2']
But instead I've got an error:
{
    "error": {
        "code": null,
        "message": "Internal Server Error"
    }
}
And in logs I see the following error:
[2019-02-11 13:51:29] api[casino].ERROR: ArgumentCountError: Too few arguments to function Directus\Application\ErrorHandlers\NotFoundHandler::__invoke(), 2 passed in D:\Git\github\directus\api\vendor\slim\slim\Slim\App.php on line 531 and exactly 3 expected in D:\Git\github\directus\api\src\core\Directus\Application\ErrorHandlers\NotFoundHandler.php:19
Stack trace:
#0 D:\Git\github\directus\api\vendor\slim\slim\Slim\App.php(531): Directus\Application\ErrorHandlers\NotFoundHandler->__invoke
#1 D:\Git\github\directus\api\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#3 D:\Git\github\directus\api\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 D:\Git\github\directus\api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#6 D:\Git\github\directus\api\vendor\wellingguzman\proxy-detection\src\ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#7 D:\Git\github\directus\api\src\core\Directus\Application\Http\Middleware\ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#8 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#9 D:\Git\github\directus\api\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#10 [internal function]: Slim\DeferredCallable->__invoke
#11 D:\Git\github\directus\api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#12 D:\Git\github\directus\api\vendor\akrabat\ip-address-middleware\src\IpAddress.php(113): Slim\App->Slim\{closure}
#13 [internal function]: RKA\Middleware\IpAddress->__invoke
#14 D:\Git\github\directus\api\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#15 [internal function]: Slim\DeferredCallable->__invoke
#16 D:\Git\github\directus\api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#17 D:\Git\github\directus\api\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(66): Slim\App->Slim\{closure}
#18 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#19 D:\Git\github\directus\api\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#20 [internal function]: Slim\DeferredCallable->__invoke
#21 D:\Git\github\directus\api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#22 D:\Git\github\directus\api\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#23 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#24 D:\Git\github\directus\api\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array
#25 [internal function]: Slim\DeferredCallable->__invoke
#26 D:\Git\github\directus\api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#27 D:\Git\github\directus\api\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#28 D:\Git\github\directus\api\vendor\slim\slim\Slim\App.php(407): Slim\App->callMiddlewareStack
#29 D:\Git\github\directus\api\vendor\slim\slim\Slim\App.php(315): Slim\App->process
#30 D:\Git\github\directus\api\src\core\Directus\Application\Application.php(161): Slim\App->run
#31 D:\Git\github\directus\api\public\index.php(5): Directus\Application\Application->run [] []

I have API instance running on my local Windows 10 machine with XAMPP 3.2 installed.  
I was using the latest build from https://github.com/directus/api.git.
Calls to core endpoints working without any problem.

Regards,
Yaroslav
